language: rust
sudo: false
os:
- linux

rust:
# Currently we require feature(process_exec).
  - nightly

# load travis-cargo
before_script:
  - pip install 'travis-cargo<0.2' --user
  - if [[ -e ~/Library/Python/2.7/bin ]]; then export PATH=~/Library/Python/2.7/bin:$PATH; fi
  - if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
  - echo PATH is $PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
